baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ezlos | Study With Me'
theme = 'LoveIt'

languageName = "English"

paginate = 10
googleAnalytics = ""
copyright= "Carlos Gomez"

enableRobotsTXT = true
enablGitInfo = true 
enablEmoji= true 

# Author config
[author]
  name = "Carlos Gomez"
  email = "ezlosswm@gmail.com"
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Posts"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "Tags"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Categories"

# Params 
[params]
  defaultTheme = "auto"
  
  dateFormat = "2006-01-02"

  # Open Graph and Twitter Cards
  title = "Ezlos | Study With Me"
  description = "A blog for beginner programmers and web developers."
  images = ["/logo.png"]

# Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "SWM"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = "Ezlos"
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = true 

 # Footer config
  [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false 
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2023 

 # (all posts) 
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # (category or tag) 
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

#  App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Ezlos SWM"
    # whether to omit favicon resource links
    noFavicon = false 
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

 # Search config
  [params.search]
	enable = true
	type = "lunr"
	contentLength = 4000
	placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
	[params.search.algolia]
	  index = ""
      appID = ""
      searchKey = "" 

 # Home page config
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      # title shown in home page (HTML format is supported)
      title = "Study With Me"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "A blog for programmers & web developers."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "All content written, is on my perspective and my learning process."
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      defaultHiddenFromHomePage = false

  [params.social]
    GitHub = "EzlosSWM"
    Twitter = "EzlosSWM"
	Instagram = "ezlosswm"
	Facebook = "PotatoAndBanana"
	Email = "ezlosswm@gmail.com"
	RSS = true 

  [params.page]
    hiddenFromHomePage = false
	fontawesome = true 
	# whether to show link to Raw Markdown content 
	linkToMardown = true 
	rssFullText = false 
	[params.page.toc]
	  # enable table of contents 
	  enable = true 
	  keepStatic = true 
	  # auto update sidebar 
	  auto = true 
	[params.page.code]
	  copy = true
	  maxShownLines = 50
	[params.page.share]
	  enable = true 
	  Twitter = true 
	  Facebook = true 
	[params.page.comment]
	  enable = false 
# Facebook comment config
    [params.page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      # automatically adapt the current theme i18n configuration when empty
      languageCode = ""
	  # LoveIt CHANGED | 0.2.10 Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]
# Markup related configuration in Hugo
[markup]
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
